"""PORTFOLIO_CONTRIBUTION / PORTFOLIO_WITHDRAWAL: explicit, narrow ledger
types for capital crossing the portfolio's managed-cash boundary.

Distinct from BUY/SELL (which only change composition — cash <-> crypto —
INSIDE the portfolio boundary, never crossing it) and distinct from TRANSFER
(a physical movement of assets between two accounts that are BOTH already
inside the portfolio boundary, e.g. two INVESTMENT_CASH accounts — no
boundary crossing).

    PORTFOLIO_CONTRIBUTION:  capital enters the tracked portfolio scope
                             (Outside portfolio -> Investment Cash)
    PORTFOLIO_WITHDRAWAL:    capital leaves the tracked portfolio scope
                             (Investment Cash -> Outside portfolio)

Row shape mirrors TRANSFER exactly (two rows, same id, opposite signs,
same fiat asset/currency) — only the `type` differs, keeping the event
semantically distinct and independently health-checkable. "Outside
portfolio" may be a tracked PERSONAL account (both legs real, trackable)
or venue="external" (money never previously in any tracked venue — reuses
the SAME external-venue convention as TRANSFER, so
core.reports.cash.compute_external_flows() picks it up with zero code
change).

compute_positions() ignores these rows entirely (they are always fiat,
skipped by the unconditional `if asset in fiat: continue` — no change
needed there). core.reports.cash's balance functions are type-agnostic and
already sum these rows correctly with zero code change.

Historical data: NO synthetic per-BUY contribution is ever generated by
this module or anything that calls it — every contribution/withdrawal row
this module builds corresponds to an event the CALLER explicitly asserts
happened (real evidence or a conscious, explicit declaration). Nothing in
core/ ever invents one from BUY/SELL rows.
"""
from __future__ import annotations

import uuid
from datetime import datetime
from decimal import Decimal
from typing import FrozenSet, List, Optional, Set, Tuple

from core.model import RawRow

CONTRIBUTION = "PORTFOLIO_CONTRIBUTION"
WITHDRAWAL = "PORTFOLIO_WITHDRAWAL"
_BOUNDARY_TYPES = frozenset({CONTRIBUTION, WITHDRAWAL})
_FIAT_DEFAULT: FrozenSet[str] = frozenset({"EUR", "CZK"})


def build_portfolio_boundary_rows(
    boundary_type: str,
    timestamp: datetime,
    asset: str,
    amount: Decimal,
    outside_venue: str,
    outside_account: Optional[str],
    inside_venue: str,
    inside_account: str,
    note: Optional[str] = None,
    boundary_id: Optional[str] = None,
    fiat: FrozenSet[str] = _FIAT_DEFAULT,
) -> Tuple[RawRow, RawRow]:
    """Pure function — builds a 2-row PORTFOLIO_CONTRIBUTION or
    PORTFOLIO_WITHDRAWAL group. No I/O.

    boundary_type == CONTRIBUTION: outside loses `amount`, inside gains it.
    boundary_type == WITHDRAWAL:   inside loses `amount`, outside gains it.

    Raises ValueError for structurally invalid input:
      - amount<=0, empty venues, boundary_type not recognized
      - inside_account empty — a boundary-crossing row must always name the
        INVESTMENT_CASH-side account explicitly; outside_account may be
        None only when outside_venue == "external"
      - asset not in `fiat` — a portfolio boundary crossing is fiat-only by
        definition; crypto never crosses it directly (a crypto SELL first,
        then a fiat withdrawal, are two separate, already-supported events)
      - outside and inside resolve to the IDENTICAL (venue, account) — a
        true no-op that would move nothing (mirrors the existing TRANSFER
        source==destination rejection in ui_facade.add_trade())
    """
    if boundary_type not in _BOUNDARY_TYPES:
        raise ValueError(f"boundary_type must be one of {sorted(_BOUNDARY_TYPES)}, got: {boundary_type!r}")
    if amount <= Decimal("0"):
        raise ValueError(f"amount must be > 0, got: {amount}")
    if not outside_venue or not outside_venue.strip():
        raise ValueError("outside_venue nesmí být prázdné")
    if not inside_venue or not inside_venue.strip():
        raise ValueError("inside_venue nesmí být prázdné")
    if not inside_account or not inside_account.strip():
        raise ValueError(
            "inside_account nesmí být prázdný — INVESTMENT_CASH strana "
            "hranice musí mít explicitní account."
        )

    asset_uc = asset.upper().strip()
    if not asset_uc:
        raise ValueError("asset nesmí být prázdný")
    fiat_set = frozenset(a.upper() for a in fiat)
    if asset_uc not in fiat_set:
        raise ValueError(
            f"asset {asset_uc!r} musí být fiat ({sorted(fiat_set)}) — portfolio "
            "boundary crossing je vždy fiat-only. Crypto nikdy nepřekračuje "
            "hranici přímo (SELL na cash, pak withdrawal, jsou dvě oddělené "
            "události)."
        )

    if boundary_id is None:
        boundary_id = f"{boundary_type}_{uuid.uuid4().hex[:12]}"

    outside_venue_norm = outside_venue.lower().strip()
    inside_venue_norm = inside_venue.lower().strip()
    outside_account_norm = (outside_account or "").strip() or None
    inside_account_norm = inside_account.strip()

    if (outside_venue_norm, outside_account_norm) == (inside_venue_norm, inside_account_norm):
        raise ValueError(
            f"outside a inside jsou identické (venue={outside_venue_norm!r}, "
            f"account={outside_account_norm!r}) — nic by se nepřesunulo."
        )

    if boundary_type == CONTRIBUTION:
        outside_amount, inside_amount = -amount, +amount
    else:
        outside_amount, inside_amount = +amount, -amount

    row_outside = RawRow(
        id=boundary_id, timestamp=timestamp, type=boundary_type,
        asset=asset_uc, amount=outside_amount, currency=asset_uc, price=Decimal("1"),
        venue=outside_venue_norm, note=note, account=outside_account_norm,
    )
    row_inside = RawRow(
        id=boundary_id, timestamp=timestamp, type=boundary_type,
        asset=asset_uc, amount=inside_amount, currency=asset_uc, price=Decimal("1"),
        venue=inside_venue_norm, note=note, account=inside_account_norm,
    )
    return row_outside, row_inside


def validate_portfolio_boundary_group(
    rows: List[RawRow],
    fiat: FrozenSet[str] = _FIAT_DEFAULT,
) -> Tuple[bool, List[str]]:
    """Validate the structural shape of a PORTFOLIO_CONTRIBUTION/WITHDRAWAL
    group (all rows sharing one id). Purely structural — does NOT require
    knowing which account has which role (see
    validate_portfolio_boundary_direction() for the role/sign cross-check,
    which DOES need that context and is applied at write time, not here)."""
    errors: List[str] = []
    boundary_rows = [r for r in rows if r.type in _BOUNDARY_TYPES]
    if not boundary_rows:
        return False, ["Skupina neobsahuje žádný PORTFOLIO_CONTRIBUTION/WITHDRAWAL řádek."]

    types_present: Set[str] = {r.type for r in boundary_rows}
    if len(types_present) != 1:
        errors.append(f"Skupina míchá typy {sorted(types_present)} — musí být jednotná.")

    if len(boundary_rows) != 2:
        errors.append(f"Musí existovat přesně 2 řádky (outside + inside), nalezeno {len(boundary_rows)}.")

    currencies = {r.currency.upper() for r in boundary_rows}
    assets = {r.asset.upper() for r in boundary_rows}
    if len(currencies) > 1 or len(assets) > 1 or currencies != assets:
        errors.append("Obě legs musí mít stejný asset/currency (fiat-only pohyb hranice).")

    fiat_set = frozenset(a.upper() for a in fiat)
    non_fiat_assets = assets - fiat_set
    if non_fiat_assets:
        errors.append(
            f"Portfolio boundary musí být fiat-only, nalezen non-fiat asset: {sorted(non_fiat_assets)}."
        )

    net = sum((r.amount for r in boundary_rows), Decimal("0"))
    if net != Decimal("0"):
        errors.append(f"Součet obou legs musí být přesně 0, je {net}.")

    if len(boundary_rows) == 2:
        amounts = sorted(r.amount for r in boundary_rows)
        if amounts[0] >= Decimal("0") or amounts[1] <= Decimal("0"):
            errors.append("Musí existovat přesně jedna kladná a jedna záporná leg (žádná nulová).")
        # Exactly one leg must be the "account required" INVESTMENT_CASH
        # side — but the "outside" leg MAY also carry an account (e.g. a
        # tracked PERSONAL account), so at least one, not exactly one.
        with_account = [r for r in boundary_rows if r.account is not None]
        if len(with_account) < 1:
            errors.append("Alespoň jedna leg musí mít explicitní account (INVESTMENT_CASH strana).")

    return (len(errors) == 0, errors)


def validate_portfolio_boundary_direction(
    rows: List[RawRow],
    boundary_type: str,
    inside_venue: str,
    inside_account: str,
) -> Tuple[bool, List[str]]:
    """Cross-check the SIGN of each leg against the declared boundary_type,
    GIVEN which (venue, account) is the INVESTMENT_CASH ("inside") side.

    This is deliberately a SEPARATE function from
    validate_portfolio_boundary_group(): knowing which leg is "inside" is
    external context (the caller's own declaration, or ultimately an
    account-role lookup), not something derivable from the two rows alone
    — a bare structural scan can't tell "outside -> inside" from
    "inside -> outside" without being told which side is which.

    CONTRIBUTION: inside leg must be POSITIVE (gains).
    WITHDRAWAL:   inside leg must be NEGATIVE (loses).

    Raises no exception — returns (ok, errors), same contract as
    validate_portfolio_boundary_group().
    """
    errors: List[str] = []
    if boundary_type not in _BOUNDARY_TYPES:
        return False, [f"boundary_type must be one of {sorted(_BOUNDARY_TYPES)}, got: {boundary_type!r}"]

    inside_venue_norm = inside_venue.lower().strip()
    inside_account_norm = inside_account.strip()

    boundary_rows = [r for r in rows if r.type == boundary_type]
    inside_legs = [
        r for r in boundary_rows
        if r.venue.lower() == inside_venue_norm and r.account == inside_account_norm
    ]
    if len(inside_legs) != 1:
        return False, [
            f"Nelze najít přesně 1 inside leg pro (venue={inside_venue_norm!r}, "
            f"account={inside_account_norm!r}), nalezeno {len(inside_legs)}."
        ]

    inside_leg = inside_legs[0]
    if boundary_type == CONTRIBUTION and inside_leg.amount <= Decimal("0"):
        errors.append(
            f"CONTRIBUTION: inside leg musí být kladný, je {inside_leg.amount} "
            "— podezření na záměnu směru (vypadá jako WITHDRAWAL)."
        )
    if boundary_type == WITHDRAWAL and inside_leg.amount >= Decimal("0"):
        errors.append(
            f"WITHDRAWAL: inside leg musí být záporný, je {inside_leg.amount} "
            "— podezření na záměnu směru (vypadá jako CONTRIBUTION)."
        )

    return (len(errors) == 0, errors)
